name = "GenomicBreeding"
uuid = "10ae3e88-9fae-48f7-b74d-53e776fee7da"
authors = ["jeffersonparil@gmail.com"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
